<a href="https://colab.research.google.com/github/dushyanthreddy000/.-The-Machine-Learning-Landscape-Exercise-Answers/blob/main/TensorFlow_2_quickstart_for_beginners.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.8.0


In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.5610621 ,  0.1818763 , -0.3396007 ,  0.81668067,  0.28056648,
        -0.06740208, -0.18907978, -0.78823453, -0.23380327,  0.6101173 ]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.05226099, 0.10985801, 0.06521644, 0.20726393, 0.12125294,
        0.08561926, 0.07581018, 0.04164069, 0.07249438, 0.16858324]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.457845

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2967 - accuracy: 0.9152
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1408 - accuracy: 0.9587
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1057 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0870 - accuracy: 0.9742
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0742 - accuracy: 0.9773


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0707 - accuracy: 0.9781 - 788ms/epoch - 3ms/step


[0.07067304104566574, 0.9781000018119812]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.48901538e-09, 7.45757589e-09, 1.08066445e-06, 2.41840346e-04,
        9.04831505e-12, 6.14906583e-07, 8.73415377e-16, 9.99753535e-01,
        8.94560060e-07, 2.05709489e-06],
       [6.57061605e-08, 4.47829152e-05, 9.99928832e-01, 2.38350240e-05,
        8.84111616e-17, 7.96234012e-09, 5.49913537e-08, 2.42906858e-11,
        2.37834251e-06, 2.21427203e-14],
       [1.77779418e-06, 9.96675253e-01, 2.60348461e-04, 4.96222237e-05,
        6.34368043e-05, 1.01150235e-05, 5.87568029e-05, 2.54197349e-03,
        3.37748526e-04, 9.94977995e-07],
       [9.99603331e-01, 2.09869569e-07, 1.36931674e-04, 4.07034889e-07,
        3.84593790e-07, 1.47605737e-04, 8.29359560e-05, 1.26549994e-05,
        3.54369445e-06, 1.20184195e-05],
       [2.70069609e-06, 1.23222961e-08, 4.35339962e-06, 1.90999771e-07,
        9.99406457e-01, 3.58141506e-06, 6.27649888e-06, 1.19173255e-05,
        4.27727036e-06, 5.60203800e-04]], dtype=float32)>

Congratulations! You have trained a machine learning model using a prebuilt dataset using the Keras API.